image: golang:1.14.2

variables:
    IMAGE_NAME: version-store-prod
    BUILD_PATH: /builds/masterback/version-store

stages:
    - deploy&copy
    - deploy&compose
    - message_on_success
    - message_on_failure


deploy&copy:
    stage: deploy&copy
    script:
        # компилируем исполняемый бинарный файл для Linux
        # - ./sh/build-linux-binary.sh  
        # Наполняем файлами директорию deploy/
        - ./sh/build-deploy-directory.sh  
        - ./.import-ssh-key.sh "$PROD_RSA_PRIVATE_KEY"
        # удаляем старую директорию на боевом сервере
        - ssh gitupdater@dockerweb.rgwork.ru 'rm -rf /home/gitupdater/'$IMAGE_NAME
        # копируем новую директорию deploy/ на боевой сервер
        - scp -pr $BUILD_PATH/deploy gitupdater@dockerweb.rgwork.ru:/home/gitupdater/$IMAGE_NAME
        # - rsync -av $BUILD_PATH/deploy gitupdater@dockerweb.rgwork.ru:/home/gitupdater/$IMAGE_NAME
        # change rights to filebeat (permition denied)
        # - ssh gitupdater@dockerweb.rgwork.ru 'chown root /home/gitupdater/'$IMAGE_NAME/configs/filebeat.yml

    only:
        - production


deploy&compose:
    stage: deploy&compose
    dependencies:
        - deploy&copy
    script:
        - ./.import-ssh-key.sh "$DEPLOY_RSA_PRIVATE_KEY"
        # !!! start real deploy and docker-compose
        - ssh gitupdater@dockerweb.rgwork.ru $IMAGE_NAME
    only:
        - production


message_on_success:
    stage: message_on_success
    allow_failure: true
    dependencies:
        - deploy&compose
    when: on_success
    script:
        # send to telegram proxy
        - curl -v http://proxy.govoru.com/?message=%E2%9C%85%20Success.%20Auto%20deploy%20on%20${CI_PROJECT_NAME}%20is%20completed,%20Pipeline:%20${CI_PIPELINE_URL}%20by%20${GITLAB_USER_LOGIN}
    only:
        - production


message_on_failure:
    stage: message_on_failure
    allow_failure: true
    dependencies:
        - deploy&compose
    when: on_failure
    script:
        # send to telegram proxy
        - curl -v http://proxy.govoru.com/?message=%E2%9D%8C%20Error.%20Auto%20deploy%20on%20${CI_PROJECT_NAME}%20is%20failed,%20Pipeline:%20${CI_PIPELINE_URL}%20by%20${GITLAB_USER_LOGIN}
    only:
        - production
