# Реализует хранилище версий документов 


version: '3'
services:
  # Кластер elasticsearch
  # E L A S T I C S E A R C H   C L U S T E R  B E G I N -----------------------------------------------------------
  # Здесь определен только один узел кластера.
  # Пример кластера из нескольких узлов смотри в проекте log-monitor
  version-store-es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    container_name: version-store-es01
    restart: unless-stopped
    environment:
      - node.name=es01
      - cluster.name=version-store-escluster
      # - discovery.seed_hosts=es02,es03
      # - cluster.initial_master_nodes=es01,es02,es03
      - cluster.initial_master_nodes=es01
      
      # вместо параметров кластера можно использовать - discovery.type=single-node.
      # Но тогда статус кластера всегда будет желтым.
      # - discovery.type=single-node

      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      # добавить threshold_enabled=false к каждой службе эластик если свободного места на диске < 10%
      # в противном случае шарды не будут двигаться
      # - cluster.routing.allocation.disk.threshold_enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    # Прямой порт скрываем чтобы не было конфликтов с другими Эластиками
    # Весь доступ пускаем через Caddy
    # ports:
    #   - 9200:9200
    volumes:
      - version-store-esdata01:/usr/share/elasticsearch/data
      # данные и скрипты для инициализации индекса
      - ./elastic_migrations:/migrations

  # E L A S T I C S E A R C H   C L U S T E R  E N D -----------------------------------------------------------
  
  

  # Caddy HTTP сервер, добавлен для
  # ограничения доступа к elasticsearch со стороны внешних программ.
  # Параметры проксирования определены в Caddyfile
  version-store-caddy:
    image: caddy:2.0.0-alpine
    container_name: version-store-caddy
    restart: unless-stopped
    ports:
      - '9096:8080'
    volumes:
      - ./configs/Caddyfile:/etc/caddy/Caddyfile
      - ./www:/www


# volumes for Elasticsearch data 
volumes:
  version-store-esdata01:

# outer network to communicate with other services 
networks:
    default:
      external:
        name: auth_proxy_network
